"""Create database

Revision ID: 74d85df25cb2
Revises: 
Create Date: 2024-06-10 19:55:40.463006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import FetchedValue

# revision identifiers, used by Alembic.
revision: str = '74d85df25cb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ADDRESS_TYPE',
    sa.Column('CD', sa.SmallInteger(), nullable=False),
    sa.Column('DESCR', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('CD')
    )
    op.create_table('APPLICATION',
    sa.Column('NUM', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('NAME', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('NUM')
    )
    op.create_index(op.f('ix_APPLICATION_NUM'), 'APPLICATION', ['NUM'], unique=False)
    op.create_table('AREA',
    sa.Column('CD', sa.Integer(), nullable=False),
    sa.Column('DESCR', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('CD')
    )
    op.create_table('AUTHORIZED_ROLE',
    sa.Column('NUMBER', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('NAME', sa.String(length=50), nullable=True),
    sa.Column('CREATION_DATE', sa.Date(), server_default=sa.text('GETDATE()'), nullable=True),
    sa.Column('EXPIRY_DATE', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('NUMBER')
    )
    op.create_table('COMMISSION_TYPE',
    sa.Column('CD', sa.SmallInteger(), nullable=False),
    sa.Column('DESCR', sa.String(length=35), nullable=True),
    sa.Column('CREATION_DATE', sa.Date(), server_default=sa.text('GETDATE()'), nullable=True),
    sa.PrimaryKeyConstraint('CD')
    )
    op.create_table('COMMISSION_VALUE_TYPE',
    sa.Column('CD', sa.SmallInteger(), nullable=False),
    sa.Column('DESCR', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('CD')
    )
    op.create_table('CONNECTOR',
    sa.Column('ID', sa.SmallInteger(), nullable=False),
    sa.Column('NAME', sa.String(length=15), nullable=False),
    sa.Column('STATUS', sa.String(length=1), nullable=False),
    sa.Column('CREATED', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('UPDATED', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('CURRENCY',
    sa.Column('ID', sa.SmallInteger(), nullable=False),
    sa.Column('CODE', sa.String(length=5), nullable=False),
    sa.Column('NAME', sa.String(length=20), nullable=True),
    sa.Column('ACTIVE_FROM', sa.DateTime(), nullable=True),
    sa.Column('RATE', sa.DECIMAL(precision=7, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('EQUIPMENT_TYPE',
    sa.Column('CD', sa.SmallInteger(), nullable=False),
    sa.Column('DESCR', sa.String(length=50), nullable=True),
    sa.Column('STATUS', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('CD')
    )
    op.create_table('KIOSK_TYPE',
    sa.Column('ID', sa.SmallInteger(), nullable=False),
    sa.Column('DESCR', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('PAYMENT_TYPE',
    sa.Column('CD', sa.SmallInteger(), nullable=False),
    sa.Column('DESCR', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('CD')
    )
    op.create_table('POLICE_STATION',
    sa.Column('CD', sa.SmallInteger(), nullable=False),
    sa.Column('DESCR', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('CD')
    )
    op.create_table('PROVIDER',
    sa.Column('ID', sa.SmallInteger(), nullable=False),
    sa.Column('AR_NAME', sa.String(length=40), nullable=False),
    sa.Column('ENG_NAME', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('SERVICE_GROUP',
    sa.Column('NO', sa.SmallInteger(), nullable=False),
    sa.Column('NAME', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('NO')
    )
    op.create_table('SERVICE_PARAMETER_TYPE',
    sa.Column('CD', sa.SmallInteger(), nullable=False),
    sa.Column('DESCR', sa.String(length=35), nullable=True),
    sa.Column('CONSTANCY', sa.String(length=1), nullable=True),
    sa.Column('DIRECTION', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('CD')
    )
    op.create_table('USER_TYPE',
    sa.Column('CD', sa.SmallInteger(), nullable=False),
    sa.Column('DESCR', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('CD')
    )
    op.create_index(op.f('ix_USER_TYPE_CD'), 'USER_TYPE', ['CD'], unique=False)
    op.create_table('ADDRESS',
    sa.Column('ID', sa.SmallInteger(), nullable=False),
    sa.Column('NAME', sa.String(length=35), nullable=False, comment='abbreviation for the place'),
    sa.Column('DETAILS', sa.String(length=65), nullable=True),
    sa.Column('FK_POLICE_STATICD', sa.SmallInteger(), nullable=True),
    sa.Column('FK_AREACD', sa.Integer(), nullable=True),
    sa.Column('FK_ADDRESS_TYPECD', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['FK_ADDRESS_TYPECD'], ['ADDRESS_TYPE.CD'], ),
    sa.ForeignKeyConstraint(['FK_AREACD'], ['AREA.CD'], ),
    sa.ForeignKeyConstraint(['FK_POLICE_STATICD'], ['POLICE_STATION.CD'], ),
    sa.PrimaryKeyConstraint('ID'),
    comment='Location of the kiosk device in the country'
    )
    op.create_index(op.f('ix_ADDRESS_FK_ADDRESS_TYPECD'), 'ADDRESS', ['FK_ADDRESS_TYPECD'], unique=False)
    op.create_index(op.f('ix_ADDRESS_FK_AREACD'), 'ADDRESS', ['FK_AREACD'], unique=False)
    op.create_index(op.f('ix_ADDRESS_FK_POLICE_STATICD'), 'ADDRESS', ['FK_POLICE_STATICD'], unique=False)
    op.create_table('COMMISSION_GROUP',
    sa.Column('CD', sa.Integer(), nullable=False),
    sa.Column('DESCR', sa.String(length=50), nullable=False),
    sa.Column('VALUE', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('FROM_VALUE', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('TO_VALUE', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('ACTIVE_DT', sa.Date(), nullable=True),
    sa.Column('SLAP', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('FK_COMMISSION_TCD', sa.SmallInteger(), nullable=True),
    sa.Column('FK_COMMISSION_VCD', sa.SmallInteger(), nullable=True),
    sa.Column('FK_PAYMENT_TYPECD', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['FK_COMMISSION_TCD'], ['COMMISSION_TYPE.CD'], ),
    sa.ForeignKeyConstraint(['FK_COMMISSION_VCD'], ['COMMISSION_VALUE_TYPE.CD'], ),
    sa.ForeignKeyConstraint(['FK_PAYMENT_TYPECD'], ['PAYMENT_TYPE.CD'], ),
    sa.PrimaryKeyConstraint('CD')
    )
    op.create_index(op.f('ix_COMMISSION_GROUP_FK_COMMISSION_TCD'), 'COMMISSION_GROUP', ['FK_COMMISSION_TCD'], unique=False)
    op.create_index(op.f('ix_COMMISSION_GROUP_FK_COMMISSION_VCD'), 'COMMISSION_GROUP', ['FK_COMMISSION_VCD'], unique=False)
    op.create_index(op.f('ix_COMMISSION_GROUP_FK_PAYMENT_TYPECD'), 'COMMISSION_GROUP', ['FK_PAYMENT_TYPECD'], unique=False)
    op.create_table('KIOSK_EQUIPMENT',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('DESCR', sa.String(length=100), nullable=True),
    sa.Column('COMPONENT_SER_NUM', sa.String(length=20), nullable=True),
    sa.Column('COMPONENT_IP_ADDRESS', sa.String(length=15), nullable=True),
    sa.Column('CREATION_DATE', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('STATUS', sa.SmallInteger(), nullable=True),
    sa.Column('START_DATE', sa.Date(), nullable=True),
    sa.Column('END_DATE', sa.Date(), nullable=True),
    sa.Column('FK_EQUIPMENT_TYCD', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['FK_EQUIPMENT_TYCD'], ['EQUIPMENT_TYPE.CD'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_KIOSK_EQUIPMENT_FK_EQUIPMENT_TYCD'), 'KIOSK_EQUIPMENT', ['FK_EQUIPMENT_TYCD'], unique=False)
    op.create_table('MODULE',
    sa.Column('ID', sa.SmallInteger(), nullable=False),
    sa.Column('NAME', sa.String(length=15), nullable=False),
    sa.Column('STATUS', sa.String(length=1), nullable=False),
    sa.Column('DESCRIPTION', sa.String(length=500), nullable=False),
    sa.Column('CREATED', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('UPDATED', sa.DateTime(), nullable=True),
    sa.Column('FK_CONNECTORID', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['FK_CONNECTORID'], ['CONNECTOR.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_MODULE_FK_CONNECTORID'), 'MODULE', ['FK_CONNECTORID'], unique=False)
    op.create_table('PERMISSION',
    sa.Column('NUMBER', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('NAME', sa.String(length=20), nullable=False),
    sa.Column('ACTIVE', sa.CHAR(length=3), nullable=False),
    sa.Column('EXPIRY_DATE', sa.Date(), nullable=True),
    sa.Column('CREATION_DATE', sa.Date(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.Column('FK_APPLICATIONNUM', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['FK_APPLICATIONNUM'], ['APPLICATION.NUM'], ),
    sa.PrimaryKeyConstraint('NUMBER')
    )
    op.create_index(op.f('ix_PERMISSION_FK_APPLICATIONNUM'), 'PERMISSION', ['FK_APPLICATIONNUM'], unique=False)
    op.create_index(op.f('ix_PERMISSION_NUMBER'), 'PERMISSION', ['NUMBER'], unique=False)
    op.create_table('SERVICE_CHARGE',
    sa.Column('CD', sa.Integer(), nullable=False),
    sa.Column('DESCR', sa.String(length=50), nullable=False),
    sa.Column('VALUE', sa.DECIMAL(precision=9, scale=2), nullable=False),
    sa.Column('FROM', sa.DECIMAL(precision=9, scale=2), nullable=False),
    sa.Column('TO', sa.DECIMAL(precision=9, scale=2), nullable=False),
    sa.Column('ACTIVE_DT', sa.Date(), nullable=True),
    sa.Column('SLAP', sa.DECIMAL(precision=9, scale=2), nullable=False),
    sa.Column('FK_COMMISSION_TCD', sa.SmallInteger(), nullable=True),
    sa.Column('FK_COMMISSION_VCD', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['FK_COMMISSION_TCD'], ['COMMISSION_TYPE.CD'], ),
    sa.ForeignKeyConstraint(['FK_COMMISSION_VCD'], ['COMMISSION_VALUE_TYPE.CD'], ),
    sa.PrimaryKeyConstraint('CD')
    )
    op.create_index(op.f('ix_SERVICE_CHARGE_CD'), 'SERVICE_CHARGE', ['CD'], unique=False)
    op.create_index(op.f('ix_SERVICE_CHARGE_FK_COMMISSION_TCD'), 'SERVICE_CHARGE', ['FK_COMMISSION_TCD'], unique=False)
    op.create_index(op.f('ix_SERVICE_CHARGE_FK_COMMISSION_VCD'), 'SERVICE_CHARGE', ['FK_COMMISSION_VCD'], unique=False)
    op.create_table('USER',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('USERNAME', sa.String(length=25), nullable=False),
    sa.Column('PASSWORD', sa.String(length=72), nullable=False),
    sa.Column('NAME', sa.String(length=60), nullable=False),
    sa.Column('NATIONAL_ID', sa.String(length=14), nullable=True),
    sa.Column('STATUS', sa.String(length=7), nullable=False),
    sa.Column('TAX_ID', sa.Integer(), nullable=True),
    sa.Column('FK_USER_TYPECD', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['FK_USER_TYPECD'], ['USER_TYPE.CD'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('USERNAME')
    )
    op.create_index(op.f('ix_USER_FK_USER_TYPECD'), 'USER', ['FK_USER_TYPECD'], unique=False)
    op.create_index(op.f('ix_USER_ID'), 'USER', ['ID'], unique=False)
    op.create_table('ASSIGNED_ROLE',
    sa.Column('ACTIVE', sa.CHAR(length=1), nullable=True),
    sa.Column('CREATION_DATE', sa.Date(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.Column('FK_AUTHORIZED_RNUMBER', sa.SmallInteger(), nullable=False),
    sa.Column('FK_USERID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FK_AUTHORIZED_RNUMBER'], ['AUTHORIZED_ROLE.NUMBER'], ),
    sa.ForeignKeyConstraint(['FK_USERID'], ['USER.ID'], ),
    sa.PrimaryKeyConstraint('FK_AUTHORIZED_RNUMBER', 'FK_USERID')
    )
    op.create_index(op.f('ix_ASSIGNED_ROLE_FK_AUTHORIZED_RNUMBER'), 'ASSIGNED_ROLE', ['FK_AUTHORIZED_RNUMBER'], unique=False)
    op.create_index(op.f('ix_ASSIGNED_ROLE_FK_USERID'), 'ASSIGNED_ROLE', ['FK_USERID'], unique=False)
    op.create_table('AUTHORITY',
    sa.Column('SERIAL', sa.Integer(), server_default=FetchedValue(), autoincrement=True, nullable=False),
    sa.Column('START_DATE', sa.Date(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.Column('END_DATE', sa.Date(), nullable=True),
    sa.Column('ACTIVE', sa.CHAR(length=1), nullable=True),
    sa.Column('FK_PERMISSION_NUMBER', sa.Integer(), nullable=False),
    sa.Column('FK_AUTHORIZED_RNUMBER', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['FK_AUTHORIZED_RNUMBER'], ['AUTHORIZED_ROLE.NUMBER'], ),
    sa.ForeignKeyConstraint(['FK_PERMISSION_NUMBER'], ['PERMISSION.NUMBER'], ),
    sa.PrimaryKeyConstraint('FK_PERMISSION_NUMBER', 'FK_AUTHORIZED_RNUMBER')
    )
    op.create_index(op.f('ix_AUTHORITY_FK_AUTHORIZED_RNUMBER'), 'AUTHORITY', ['FK_AUTHORIZED_RNUMBER'], unique=False)
    op.create_index(op.f('ix_AUTHORITY_FK_PERMISSION_NUMBER'), 'AUTHORITY', ['FK_PERMISSION_NUMBER'], unique=False)
    op.create_table('KIOSK_FAMILY',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('ACCOUNT_NO', sa.Numeric(precision=10), nullable=False),
    sa.Column('AR_NAME', sa.String(length=40), nullable=False),
    sa.Column('ENG_NAME', sa.String(length=40), nullable=False),
    sa.Column('TYPE', sa.String(length=1), nullable=True),
    sa.Column('DESCR', sa.String(length=100), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(), nullable=True),
    sa.Column('STATUS', sa.String(length=1), nullable=True),
    sa.Column('DELETED_FLAG', sa.SmallInteger(), nullable=True),
    sa.Column('FK_COMMISSION_GCD', sa.Integer(), nullable=True),
    sa.Column('FK_SERVICE_CHARCD', sa.Integer(), nullable=True),
    sa.Column('FK_SERVICE_GROUNO', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['FK_COMMISSION_GCD'], ['COMMISSION_GROUP.CD'], ),
    sa.ForeignKeyConstraint(['FK_SERVICE_CHARCD'], ['SERVICE_CHARGE.CD'], ),
    sa.ForeignKeyConstraint(['FK_SERVICE_GROUNO'], ['SERVICE_GROUP.NO'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_KIOSK_FAMILY_FK_COMMISSION_GCD'), 'KIOSK_FAMILY', ['FK_COMMISSION_GCD'], unique=False)
    op.create_index(op.f('ix_KIOSK_FAMILY_FK_SERVICE_CHARCD'), 'KIOSK_FAMILY', ['FK_SERVICE_CHARCD'], unique=False)
    op.create_index(op.f('ix_KIOSK_FAMILY_FK_SERVICE_GROUNO'), 'KIOSK_FAMILY', ['FK_SERVICE_GROUNO'], unique=False)
    op.create_table('MODULE_PARAMETER',
    sa.Column('ID', sa.SmallInteger(), nullable=False),
    sa.Column('KEY', sa.String(), nullable=False),
    sa.Column('VALUE', sa.String(), nullable=False),
    sa.Column('DESCRIPTION', sa.String(length=500), nullable=False),
    sa.Column('CREATED', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('UPDATED', sa.DateTime(), nullable=True),
    sa.Column('FK_MODULEID', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['FK_MODULEID'], ['MODULE.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_MODULE_PARAMETER_FK_MODULEID'), 'MODULE_PARAMETER', ['FK_MODULEID'], unique=False)
    op.create_table('SERVICE',
    sa.Column('ID', sa.SmallInteger(), nullable=False),
    sa.Column('AR_NAME', sa.String(length=40), nullable=True),
    sa.Column('ENG_NAME', sa.String(length=40), nullable=True),
    sa.Column('FK_MODULEID', sa.SmallInteger(), nullable=True),
    sa.Column('FK_PROVIDERID', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['FK_MODULEID'], ['MODULE.ID'], ),
    sa.ForeignKeyConstraint(['FK_PROVIDERID'], ['PROVIDER.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_SERVICE_FK_MODULEID'), 'SERVICE', ['FK_MODULEID'], unique=False)
    op.create_index(op.f('ix_SERVICE_FK_PROVIDERID'), 'SERVICE', ['FK_PROVIDERID'], unique=False)
    op.create_index(op.f('ix_SERVICE_ID'), 'SERVICE', ['ID'], unique=False)
    op.create_table('USER_LOG',
    sa.Column('DATE', sa.Date(), nullable=False),
    sa.Column('TIME', sa.Time(), nullable=False),
    sa.Column('FK_USERID', sa.Integer(), nullable=False),
    sa.Column('FK_PERMISSION_NUMBER', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['FK_PERMISSION_NUMBER'], ['PERMISSION.NUMBER'], ),
    sa.ForeignKeyConstraint(['FK_USERID'], ['USER.ID'], ),
    sa.PrimaryKeyConstraint('DATE', 'TIME', 'FK_USERID', name='idO')
    )
    op.create_index(op.f('ix_USER_LOG_DATE'), 'USER_LOG', ['DATE'], unique=False)
    op.create_index(op.f('ix_USER_LOG_FK_PERMISSION_NUMBER'), 'USER_LOG', ['FK_PERMISSION_NUMBER'], unique=False)
    op.create_index(op.f('ix_USER_LOG_FK_USERID'), 'USER_LOG', ['FK_USERID'], unique=False)
    op.create_index(op.f('ix_USER_LOG_TIME'), 'USER_LOG', ['TIME'], unique=False)
    op.create_table('KIOSK',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('ACCOUNT_NO', sa.Numeric(precision=10), nullable=False),
    sa.Column('AR_NAME', sa.String(length=40), nullable=False),
    sa.Column('ENG_NAME', sa.String(length=40), nullable=False),
    sa.Column('DESCR', sa.String(length=100), nullable=True),
    sa.Column('CREATION_DATE', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('UPDATED_DATE', sa.DateTime(), nullable=True),
    sa.Column('STATUS', sa.String(length=1), nullable=True),
    sa.Column('DELETED_FLAG', sa.SmallInteger(), nullable=True),
    sa.Column('CD_PART1', sa.SmallInteger(), nullable=True),
    sa.Column('CD_PART2', sa.SmallInteger(), nullable=True),
    sa.Column('COMMISSION_CHECK', sa.String(length=1), nullable=True),
    sa.Column('SERVICE_GROUP_CHECK', sa.String(length=1), nullable=True),
    sa.Column('SERVICE_CHARGE_CHECK', sa.String(length=1), nullable=True),
    sa.Column('FK_SERVICE_GROUNO', sa.SmallInteger(), nullable=True),
    sa.Column('FK_ADDRESSID', sa.SmallInteger(), nullable=True),
    sa.Column('FK_KIOSK_FAMILYID', sa.Integer(), nullable=True),
    sa.Column('FK_COMMISSION_GCD', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['FK_ADDRESSID'], ['ADDRESS.ID'], ),
    sa.ForeignKeyConstraint(['FK_COMMISSION_GCD'], ['COMMISSION_GROUP.CD'], ),
    sa.ForeignKeyConstraint(['FK_KIOSK_FAMILYID'], ['KIOSK_FAMILY.ID'], ),
    sa.ForeignKeyConstraint(['FK_SERVICE_GROUNO'], ['SERVICE_GROUP.NO'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_KIOSK_FK_ADDRESSID'), 'KIOSK', ['FK_ADDRESSID'], unique=False)
    op.create_index(op.f('ix_KIOSK_FK_COMMISSION_GCD'), 'KIOSK', ['FK_COMMISSION_GCD'], unique=False)
    op.create_index(op.f('ix_KIOSK_FK_KIOSK_FAMILYID'), 'KIOSK', ['FK_KIOSK_FAMILYID'], unique=False)
    op.create_index(op.f('ix_KIOSK_FK_SERVICE_GROUNO'), 'KIOSK', ['FK_SERVICE_GROUNO'], unique=False)
    op.create_table('SERVICE_PARAMETER',
    sa.Column('SER', sa.SmallInteger(), nullable=False),
    sa.Column('SERVICE_VALUE', sa.String(length=200), nullable=False),
    sa.Column('FK_SERVICEID', sa.SmallInteger(), nullable=False),
    sa.Column('FK_SERVICE_PARA_TYPE_CD', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['FK_SERVICEID'], ['SERVICE.ID'], ),
    sa.ForeignKeyConstraint(['FK_SERVICE_PARA_TYPE_CD'], ['SERVICE_PARAMETER_TYPE.CD'], ),
    sa.PrimaryKeyConstraint('SER')
    )
    op.create_index(op.f('ix_SERVICE_PARAMETER_FK_SERVICEID'), 'SERVICE_PARAMETER', ['FK_SERVICEID'], unique=False)
    op.create_index(op.f('ix_SERVICE_PARAMETER_FK_SERVICE_PARA_TYPE_CD'), 'SERVICE_PARAMETER', ['FK_SERVICE_PARA_TYPE_CD'], unique=False)
    op.create_table('SERVICE_PRICE',
    sa.Column('ID', sa.SmallInteger(), nullable=False),
    sa.Column('STDT', sa.Date(), server_default=sa.text('GETDATE()'), nullable=False),
    sa.Column('ENDDT', sa.Date(), nullable=True),
    sa.Column('PRICE_VALUE', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('MAX_VALUE', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('TYPE', sa.String(length=8), nullable=True),
    sa.Column('LIST_VALUE', sa.String(length=36), nullable=True),
    sa.Column('FK_SERVICEID', sa.SmallInteger(), nullable=True),
    sa.Column('FK_CURRENCYID', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['FK_CURRENCYID'], ['CURRENCY.ID'], ),
    sa.ForeignKeyConstraint(['FK_SERVICEID'], ['SERVICE.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_SERVICE_PRICE_FK_CURRENCYID'), 'SERVICE_PRICE', ['FK_CURRENCYID'], unique=False)
    op.create_index(op.f('ix_SERVICE_PRICE_FK_SERVICEID'), 'SERVICE_PRICE', ['FK_SERVICEID'], unique=False)
    op.create_table('SERVICE_SERVICEGROUP',
    sa.Column('FK_SERVICEID', sa.SmallInteger(), nullable=False),
    sa.Column('FK_SERVICE_GROUNO', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['FK_SERVICEID'], ['SERVICE.ID'], ),
    sa.ForeignKeyConstraint(['FK_SERVICE_GROUNO'], ['SERVICE_GROUP.NO'], ),
    sa.PrimaryKeyConstraint('FK_SERVICEID', 'FK_SERVICE_GROUNO')
    )
    op.create_index(op.f('ix_SERVICE_SERVICEGROUP_FK_SERVICEID'), 'SERVICE_SERVICEGROUP', ['FK_SERVICEID'], unique=False)
    op.create_index(op.f('ix_SERVICE_SERVICEGROUP_FK_SERVICE_GROUNO'), 'SERVICE_SERVICEGROUP', ['FK_SERVICE_GROUNO'], unique=False)
    op.create_table('USER_LOG_HISTORY',
    sa.Column('OLD_DATA', sa.String(length=35), nullable=True),
    sa.Column('AFF_FIELD', sa.String(length=10), nullable=True),
    sa.Column('AMOUNT_PAID', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('FK_USER_LOGDATE', sa.Date(), nullable=False),
    sa.Column('FK_USER_LOGTIME', sa.Time(), nullable=False),
    sa.Column('FK_USER_LOGFK_USERID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FK_USER_LOGDATE', 'FK_USER_LOGTIME', 'FK_USER_LOGFK_USERID'], ['USER_LOG.DATE', 'USER_LOG.TIME', 'USER_LOG.FK_USERID'], ),
    sa.PrimaryKeyConstraint('FK_USER_LOGDATE', 'FK_USER_LOGTIME', 'FK_USER_LOGFK_USERID', name='idP')
    )
    op.create_index(op.f('ix_USER_LOG_HISTORY_FK_USER_LOGDATE'), 'USER_LOG_HISTORY', ['FK_USER_LOGDATE'], unique=False)
    op.create_index(op.f('ix_USER_LOG_HISTORY_FK_USER_LOGFK_USERID'), 'USER_LOG_HISTORY', ['FK_USER_LOGFK_USERID'], unique=False)
    op.create_index(op.f('ix_USER_LOG_HISTORY_FK_USER_LOGTIME'), 'USER_LOG_HISTORY', ['FK_USER_LOGTIME'], unique=False)
    op.create_table('ASSIGNED_EQUIPMENT',
    sa.Column('TIMESTAMP', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('START_DATE', sa.Date(), nullable=False),
    sa.Column('END_DATE', sa.Date(), nullable=True),
    sa.Column('STATUS', sa.SmallInteger(), nullable=True),
    sa.Column('FK_KIOSKID', sa.Integer(), nullable=False),
    sa.Column('FK_KIOSK_EQUIPMID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FK_KIOSKID'], ['KIOSK.ID'], ),
    sa.ForeignKeyConstraint(['FK_KIOSK_EQUIPMID'], ['KIOSK_EQUIPMENT.ID'], ),
    sa.PrimaryKeyConstraint('TIMESTAMP', 'FK_KIOSKID', 'FK_KIOSK_EQUIPMID')
    )
    op.create_index(op.f('ix_ASSIGNED_EQUIPMENT_FK_KIOSKID'), 'ASSIGNED_EQUIPMENT', ['FK_KIOSKID'], unique=False)
    op.create_index(op.f('ix_ASSIGNED_EQUIPMENT_FK_KIOSK_EQUIPMID'), 'ASSIGNED_EQUIPMENT', ['FK_KIOSK_EQUIPMID'], unique=False)
    op.create_table('KIOSK_OPERATOR_LOG',
    sa.Column('ID', sa.Numeric(precision=14), nullable=False),
    sa.Column('IP_ADDRESS', sa.String(length=15), nullable=True),
    sa.Column('ENTRYSTAMP', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('AFF_FIELD', sa.Numeric(precision=10), nullable=False),
    sa.Column('AFF_FIELD2', sa.Numeric(precision=10), nullable=True),
    sa.Column('TYPE', sa.String(length=1), nullable=True),
    sa.Column('FK_KIOSKID', sa.Integer(), nullable=True),
    sa.Column('FK_PERMISSION_NUMBER', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['FK_KIOSKID'], ['KIOSK.ID'], ),
    sa.ForeignKeyConstraint(['FK_PERMISSION_NUMBER'], ['PERMISSION.NUMBER'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_KIOSK_OPERATOR_LOG_FK_KIOSKID'), 'KIOSK_OPERATOR_LOG', ['FK_KIOSKID'], unique=False)
    op.create_index(op.f('ix_KIOSK_OPERATOR_LOG_FK_PERMISSION_NUMBER'), 'KIOSK_OPERATOR_LOG', ['FK_PERMISSION_NUMBER'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_KIOSK_OPERATOR_LOG_FK_PERMISSION_NUMBER'), table_name='KIOSK_OPERATOR_LOG')
    op.drop_index(op.f('ix_KIOSK_OPERATOR_LOG_FK_KIOSKID'), table_name='KIOSK_OPERATOR_LOG')
    op.drop_table('KIOSK_OPERATOR_LOG')
    op.drop_index(op.f('ix_ASSIGNED_EQUIPMENT_FK_KIOSK_EQUIPMID'), table_name='ASSIGNED_EQUIPMENT')
    op.drop_index(op.f('ix_ASSIGNED_EQUIPMENT_FK_KIOSKID'), table_name='ASSIGNED_EQUIPMENT')
    op.drop_table('ASSIGNED_EQUIPMENT')
    op.drop_index(op.f('ix_USER_LOG_HISTORY_FK_USER_LOGTIME'), table_name='USER_LOG_HISTORY')
    op.drop_index(op.f('ix_USER_LOG_HISTORY_FK_USER_LOGFK_USERID'), table_name='USER_LOG_HISTORY')
    op.drop_index(op.f('ix_USER_LOG_HISTORY_FK_USER_LOGDATE'), table_name='USER_LOG_HISTORY')
    op.drop_table('USER_LOG_HISTORY')
    op.drop_index(op.f('ix_SERVICE_SERVICEGROUP_FK_SERVICE_GROUNO'), table_name='SERVICE_SERVICEGROUP')
    op.drop_index(op.f('ix_SERVICE_SERVICEGROUP_FK_SERVICEID'), table_name='SERVICE_SERVICEGROUP')
    op.drop_table('SERVICE_SERVICEGROUP')
    op.drop_index(op.f('ix_SERVICE_PRICE_FK_SERVICEID'), table_name='SERVICE_PRICE')
    op.drop_index(op.f('ix_SERVICE_PRICE_FK_CURRENCYID'), table_name='SERVICE_PRICE')
    op.drop_table('SERVICE_PRICE')
    op.drop_index(op.f('ix_SERVICE_PARAMETER_FK_SERVICE_PARA_TYPE_CD'), table_name='SERVICE_PARAMETER')
    op.drop_index(op.f('ix_SERVICE_PARAMETER_FK_SERVICEID'), table_name='SERVICE_PARAMETER')
    op.drop_table('SERVICE_PARAMETER')
    op.drop_index(op.f('ix_KIOSK_FK_SERVICE_GROUNO'), table_name='KIOSK')
    op.drop_index(op.f('ix_KIOSK_FK_KIOSK_FAMILYID'), table_name='KIOSK')
    op.drop_index(op.f('ix_KIOSK_FK_COMMISSION_GCD'), table_name='KIOSK')
    op.drop_index(op.f('ix_KIOSK_FK_ADDRESSID'), table_name='KIOSK')
    op.drop_table('KIOSK')
    op.drop_index(op.f('ix_USER_LOG_TIME'), table_name='USER_LOG')
    op.drop_index(op.f('ix_USER_LOG_FK_USERID'), table_name='USER_LOG')
    op.drop_index(op.f('ix_USER_LOG_FK_PERMISSION_NUMBER'), table_name='USER_LOG')
    op.drop_index(op.f('ix_USER_LOG_DATE'), table_name='USER_LOG')
    op.drop_table('USER_LOG')
    op.drop_index(op.f('ix_SERVICE_ID'), table_name='SERVICE')
    op.drop_index(op.f('ix_SERVICE_FK_PROVIDERID'), table_name='SERVICE')
    op.drop_index(op.f('ix_SERVICE_FK_MODULEID'), table_name='SERVICE')
    op.drop_table('SERVICE')
    op.drop_index(op.f('ix_MODULE_PARAMETER_FK_MODULEID'), table_name='MODULE_PARAMETER')
    op.drop_table('MODULE_PARAMETER')
    op.drop_index(op.f('ix_KIOSK_FAMILY_FK_SERVICE_GROUNO'), table_name='KIOSK_FAMILY')
    op.drop_index(op.f('ix_KIOSK_FAMILY_FK_SERVICE_CHARCD'), table_name='KIOSK_FAMILY')
    op.drop_index(op.f('ix_KIOSK_FAMILY_FK_COMMISSION_GCD'), table_name='KIOSK_FAMILY')
    op.drop_table('KIOSK_FAMILY')
    op.drop_index(op.f('ix_AUTHORITY_FK_PERMISSION_NUMBER'), table_name='AUTHORITY')
    op.drop_index(op.f('ix_AUTHORITY_FK_AUTHORIZED_RNUMBER'), table_name='AUTHORITY')
    op.drop_table('AUTHORITY')
    op.drop_index(op.f('ix_ASSIGNED_ROLE_FK_USERID'), table_name='ASSIGNED_ROLE')
    op.drop_index(op.f('ix_ASSIGNED_ROLE_FK_AUTHORIZED_RNUMBER'), table_name='ASSIGNED_ROLE')
    op.drop_table('ASSIGNED_ROLE')
    op.drop_index(op.f('ix_USER_ID'), table_name='USER')
    op.drop_index(op.f('ix_USER_FK_USER_TYPECD'), table_name='USER')
    op.drop_table('USER')
    op.drop_index(op.f('ix_SERVICE_CHARGE_FK_COMMISSION_VCD'), table_name='SERVICE_CHARGE')
    op.drop_index(op.f('ix_SERVICE_CHARGE_FK_COMMISSION_TCD'), table_name='SERVICE_CHARGE')
    op.drop_index(op.f('ix_SERVICE_CHARGE_CD'), table_name='SERVICE_CHARGE')
    op.drop_table('SERVICE_CHARGE')
    op.drop_index(op.f('ix_PERMISSION_NUMBER'), table_name='PERMISSION')
    op.drop_index(op.f('ix_PERMISSION_FK_APPLICATIONNUM'), table_name='PERMISSION')
    op.drop_table('PERMISSION')
    op.drop_index(op.f('ix_MODULE_FK_CONNECTORID'), table_name='MODULE')
    op.drop_table('MODULE')
    op.drop_index(op.f('ix_KIOSK_EQUIPMENT_FK_EQUIPMENT_TYCD'), table_name='KIOSK_EQUIPMENT')
    op.drop_table('KIOSK_EQUIPMENT')
    op.drop_index(op.f('ix_COMMISSION_GROUP_FK_PAYMENT_TYPECD'), table_name='COMMISSION_GROUP')
    op.drop_index(op.f('ix_COMMISSION_GROUP_FK_COMMISSION_VCD'), table_name='COMMISSION_GROUP')
    op.drop_index(op.f('ix_COMMISSION_GROUP_FK_COMMISSION_TCD'), table_name='COMMISSION_GROUP')
    op.drop_table('COMMISSION_GROUP')
    op.drop_index(op.f('ix_ADDRESS_FK_POLICE_STATICD'), table_name='ADDRESS')
    op.drop_index(op.f('ix_ADDRESS_FK_AREACD'), table_name='ADDRESS')
    op.drop_index(op.f('ix_ADDRESS_FK_ADDRESS_TYPECD'), table_name='ADDRESS')
    op.drop_table('ADDRESS')
    op.drop_index(op.f('ix_USER_TYPE_CD'), table_name='USER_TYPE')
    op.drop_table('USER_TYPE')
    op.drop_table('SERVICE_PARAMETER_TYPE')
    op.drop_table('SERVICE_GROUP')
    op.drop_table('PROVIDER')
    op.drop_table('POLICE_STATION')
    op.drop_table('PAYMENT_TYPE')
    op.drop_table('KIOSK_TYPE')
    op.drop_table('EQUIPMENT_TYPE')
    op.drop_table('CURRENCY')
    op.drop_table('CONNECTOR')
    op.drop_table('COMMISSION_VALUE_TYPE')
    op.drop_table('COMMISSION_TYPE')
    op.drop_table('AUTHORIZED_ROLE')
    op.drop_table('AREA')
    op.drop_index(op.f('ix_APPLICATION_NUM'), table_name='APPLICATION')
    op.drop_table('APPLICATION')
    op.drop_table('ADDRESS_TYPE')
    # ### end Alembic commands ###
